path = ["/home/cory/bin", "/bin", "/sbin", "/usr/bin", "/usr/sbin", "/usr/X11R7/bin", "/usr/pkg/bin", "/usr/pkg/sbin", "/usr/games", "/usr/local/bin", "/usr/local/sbin", "/home/cory/.xmonad"]
prompt = "default"

[env]
CMD_DURATION_MS = "10"
COLORFGBG = "default;default"
COLORTERM = "rxvt-xpm"
DISPLAY = ":0"
EDITOR = "vim"
HOME = "/home/cory"
LANG = "en_US.UTF-8"
LC_ALL = ""
LC_CTYPE = "en_US.UTF-8"
LOGNAME = "cory"
PWD = "/home/cory"
SHELL = "/usr/pkg/bin/bash"
SHLVL = "2"
TERM = "rxvt"
USER = "cory"
WINDOWID = "8388615"
WINDOWPATH = "5"
XAUTHORITY = "/home/cory/.Xauthority"
_ = "/usr/pkg/bin/nu"

[line_editor]
edit_mode = "vi"
